### ISSUE TITLE
Manage to hidden section menu in User 'My Setting'

### ISSUE THREAD

**Issue by Fyn5** [zaviagodev/frappe#107]
Hidden or default setting for Notification by Email and Third Party Authentication

![Image](https://github.com/zaviagodev/frappe/assets/120152401/54c00506-bb38-4185-8de4-9861825bc1b6)

**Comment by chomchuen** [comment]
**Hided all sections below.✅**

- [ ] - [ ] Document Flow
- [ ] Email
- [ ] Third Party Authentication

![Image](https://github.com/zaviagodev/frappe/assets/120152434/6bc8a0f1-e4ec-4624-8781-d76bc3249e0f)
