### ISSUE TITLE
"Add Tracking" modal & Shipping Tab - Sales invoice/Shipping tab

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#109]
### **Everything on this tab is 'Read only' except 'Add Tracking' button.**
**you can check the detail of every fields on this tab on Figma**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/4889e900-a1ab-41de-bbce-2b4f24e5c9c0)

**Comment by chomchuen** [comment]
**Can not add tracking no**. if Sales invoice = overdue.

<img width="817" alt="Screen Shot 2566-12-22 at 09 49 39" src="https://github.com/zaviagodev/frappe/assets/120152434/87f6b8cf-1d83-4e8c-817e-7c584a81e592">

**Comment by John-zaviago** [comment]
- [ ] Hide the shipping tab- when SINV doctyp = draft status

**Comment by chomchuen** [comment]
![Image](https://github.com/zaviagodev/frappe/assets/120152434/a67a9d3c-b07f-48bc-9135-f78cb55eedc1)
