### ISSUE TITLE
"Get information from main item" button - website item doctype

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#117]
### Objection:
Create functionality to "Get information from main item" button.

---
In Additional Info tab on Website item doctype, have 'Get information from Main item' button. 
Function of this button is "**Getting 1. Short Description 
2. Long Description 
3. Return & Refund policy title/description
4. Shipping info title/description" from master item.**

//if website item already have it own Short Description, Long Description, Return & Refund policy title/description, Shipping info title/description, **'Get information from Main item' button will replace exists text in 6 fields.** 

![Image](https://github.com/zaviagodev/frappe/assets/120152434/11fb89a0-1e87-4b5c-841b-c44beffad0ee)

**Comment by chomchuen** [comment]
1. Get data but do not save document (let users save it by themself).
2. Short description doesn't work
<img width="1098" alt="Screen Shot 2567-01-04 at 18 25 39" src="https://github.com/zaviagodev/frappe/assets/120152434/54fdf3c5-c4f3-4bc8-a190-67e6acc4890c">
<img width="1092" alt="Screen Shot 2567-01-04 at 18 25 53" src="https://github.com/zaviagodev/frappe/assets/120152434/e3aa3779-7b10-41f5-a820-4303f08e49e5">

**Comment by chomchuen** [comment]
**Done both✅**
![Screen Shot 2567-01-05 at 10 41 21](https://github.com/zaviagodev/frappe/assets/120152434/256770b6-fe1c-439c-a808-a224d411503e)

**Comment by chomchuen** [comment]
Can you find which function that automatically fetch Short/long description from master item to website item and disable it?

-> If users want website item to use same short/long (also policy&shipping) description as a master item, users must manually click on the "Get information from main item" button. 
![Image](https://github.com/zaviagodev/frappe/assets/120152434/2b8b4838-6528-4e83-87e7-5a6195afc9e8)

----
How to reproduce issue.

1. Open master item & website item at the same time
2. Change short and/or long description of master item
3. Change to website item tab.
4. Refresh the page and you will see that short and/or long description was updated automatically.

**Comment by Muzmal** [comment]
( Pending Review )

**Comment by chomchuen** [comment]
Fixed✅

Master item | Website item
![Screen Shot 2567-01-22 at 13 49 07](https://github.com/zaviagodev/frappe/assets/120152434/84d5f6dd-e874-420e-a597-b171a656c6cb)
