### ISSUE TITLE
Hide 'View' button from /app/customer/

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#123]
![Image](https://github.com/zaviagodev/frappe/assets/120152434/37fee211-6394-4950-8ea1-d58eeb451480)

**Comment by chomchuen** [comment]
Can't do this due to JS issue on apps.hosting

**Comment by chomchuen** [comment]
on beeta.zaviago.com

![Image](https://github.com/zaviagodev/frappe/assets/120152434/f0813cb8-21ea-46f8-b9bb-ec7a0fe8ccfc)

**Comment by Muzmal** [comment]
Done

**Comment by chomchuen** [comment]
on apps.hosting
![Screen Shot 2566-12-18 at 15 15 53](https://github.com/zaviagodev/frappe/assets/120152434/a59ee88d-b1dc-412e-b252-d55bb21e7b90)
