### ISSUE TITLE
Sales invoice didn't perform calculation automatically.

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#132]
### Problem:
**Default** - Frappe performs calculations like Vat/Taxes calculation, grand total (with discount) without pressing any event buttons.
**Current** - Users need to click some event button to update/calculate the value.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/7036f667-f1bf-41b0-aae9-9cfeb96e103c)
----
### Objection:
**Investigate what cased this bug🔍🔍.**

**Comment by John-zaviago** [comment]
@chomchuen please send link where it happened

**Comment by umer2001** [comment]
https://github.com/zaviagodev/frappe/assets/35496058/62960307-9e2b-460b-a911-319138976ceb

**Comment by chomchuen** [comment]
Additional Discount feature working fine now on apps.hosting site✅.

But this issue also happens with **Taxes and Charges** as well.
<img width="1334" alt="Screen Shot 2566-12-21 at 09 57 32" src="https://github.com/zaviagodev/frappe/assets/120152434/6c13bcc8-89c8-4d25-8976-5958b92fea26">

Another Frappe site /app/sales-invoice/new-sales-invoice
<img width="1324" alt="Screen Shot 2566-12-21 at 10 00 13" src="https://github.com/zaviagodev/frappe/assets/120152434/1cd61007-d203-4139-9653-4c271e760ae4">

**Comment by John-zaviago** [comment]
@chomchuen is this issue still on goning?

**Comment by John-zaviago** [comment]
@chomchuen is the any addtional update on this?

**Comment by chomchuen** [comment]
@John-zaviago This issue is still persisting. 

![Image](https://github.com/zaviagodev/frappe/assets/120152434/966d0ecb-ef53-4cd1-8a3a-ea63857be04d)

**Comment by John-zaviago** [comment]
@chomchuen please test again

**Comment by chomchuen** [comment]
Taxes and Charge still has this issue.
https://www.loom.com/share/ec48a37b61714b029404cbb1192148ea?sid=65bbe5c7-01c9-46ee-97c3-601b86388060

**Comment by umer2001** [comment]
@chomchuen & @John-zaviago ,

Fixed it in **tmp.zaviago.com** and **apps.hosting.zaviago.com** 😀

relative commit https://github.com/zaviagodev/zaviagocore/commit/b6b190ca58ba2099f018936543c9de5b531218ed

**Comment by John-zaviago** [comment]
Looking good, seem work now. thank you. Closing this
