### ISSUE TITLE
Bugs🐞 on Sales invoice and Payment entry doctype

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#133]
### Objection:
- Investigate what caused this bug🔍🔍.
----
### Where?
- Sales invoice doctype.
- Payment Entry doctype.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/b7567342-41e2-4c94-95ba-f1e2110e101d)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/25de7063-907a-492c-bb9d-c3f33a61ad93)

![Image](https://github.com/zaviagodev/frappe/assets/120152434/12fbb38e-3895-4502-be8f-db2fcdd6cdbd)

**Comment by Muzmal** [comment]
It seems that server is not handling and rendering the fields properly. If you go to other tabs or save something then it works.
