### ISSUE TITLE
Set 1st email/phone no. to be primary /app/contact

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#172]
This fixed✅
### Conditions:
Only if users didn't check **'Is Primary'** in Email ID table. and
Only if users didn't check **'Is Primary Phone' and 'Is Primary Mobiles'** in contact number table.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/ef8ff330-ae77-487b-b6e6-986b969662d7)

**Comment by chomchuen** [comment]
**Function works correctly✅ but has 'contact not found' warning. Please investigate and fix this issue.**
<img width="1350" alt="Screen Shot 2567-01-09 at 15 23 29" src="https://github.com/zaviagodev/frappe/assets/120152434/f0c83b5d-4a60-428c-b08f-9e540011f6ee">

<img width="1285" alt="Screen Shot 2567-01-09 at 15 24 39" src="https://github.com/zaviagodev/frappe/assets/120152434/4aa26406-6724-48e8-9d16-a7f570244892">
<img width="1095" alt="Screen Shot 2567-01-09 at 15 26 20" src="https://github.com/zaviagodev/frappe/assets/120152434/0b20812b-732e-4385-b839-1a1d4c71e3a1">

**Comment by chomchuen** [comment]
I found 2 new issue related to this function.

----

**Issue 1**
1. Contact below is contact that I left all primary checkbox as a blank. Then, I deselected one of it.
and wait for a moment (or sometime refresh the page). Checkbox that I've deselected was selected again.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/8315ed82-e736-4ab5-99d8-f9ed3d165e25)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/f2a36032-6c3b-439e-a47c-0bf27fc6734a)

----
Fixed✅
**Issue 2**
2. Contact didn't display email/phone number in preview even it's primary.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/5f3d3574-ade9-41f8-a51c-68eff62ef8e6)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/84c7e2bf-3fc7-4b38-a5a0-314eb04341bd)


**How to reproduce an issue.**

1. Go to customer
2. Add contact by using this button
![Image](https://github.com/zaviagodev/frappe/assets/120152434/56c083c8-9134-445a-a1cb-7f931aa5aa76)
3. Add detail and don't check primary option.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/8d2ff327-8f76-482e-8d70-b092b64dcff7)
4. Contact is created without primary mark.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/33618464-c4c2-4379-bf1f-ce240acb3126)
5. Go into that contact again and you will see that primary option is just checked.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/23bc2b69-4235-4a11-a52d-84e47e99f735)
6. Come back to linked customer and you will see the problem.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/d24d5740-fb06-447b-b796-91ac777bbf07)

**Comment by Muzmal** [comment]
Fixed!! Now user can deselect the option to make primary.

**Comment by chomchuen** [comment]
Issue 1 is fixed.✅ Issue 2 is still persisting.❌

**Comment by chomchuen** [comment]
Fixed✅
~~Issue no.2 is still persisting.~~
![Screen Shot 2567-01-24 at 18 04 31](https://github.com/zaviagodev/frappe/assets/120152434/e41ca946-1f04-42f3-9128-0159e72ab7e1)

**Comment by chomchuen** [comment]
This comment is fixed✅

------
**Expectation**⤵️
If meet the condition, phone no. will be both 'Primary Phone' and 'Primary Mobile' like the image below.
<img width="567" alt="Screen Shot 2567-01-26 at 09 26 56" src="https://github.com/zaviagodev/frappe/assets/120152434/83a8c73d-1941-476f-b9ab-b82208b3af55">

**What's happening now.**
'No Primary Mobile'
<img width="612" alt="Screen Shot 2567-01-26 at 09 27 56" src="https://github.com/zaviagodev/frappe/assets/120152434/c1a9181f-bdd1-4087-a790-6ecadfab3cc4">

The issue above caused this issue. No Primary Mobile, then no phone mobile no. display here.
<img width="1102" alt="Screen Shot 2567-01-26 at 09 28 47" src="https://github.com/zaviagodev/frappe/assets/120152434/fbac87c0-311a-4a0b-adbc-854f561e7ce2">

**Comment by chomchuen** [comment]
@Muzmal This is persisting. Can you check from this video?

- [x] 'No Primary Mobile' issue
- [ ] Customer Primary Contact was selected but no email id and phone no. show up.

https://www.loom.com/share/d30a04b312be4d7283de145b44f83d2d?sid=3ab93ba0-fac0-47b4-b6f2-0b870bae881c

**Comment by Muzmal** [comment]
Fixed. you can check

**Comment by chomchuen** [comment]
<img width="1360" alt="Screen Shot 2567-02-07 at 14 01 48" src="https://github.com/zaviagodev/frappe/assets/120152434/d1177d58-81e4-49ef-bf59-068961f038b3">
<img width="1312" alt="Screen Shot 2567-02-07 at 14 04 43" src="https://github.com/zaviagodev/frappe/assets/120152434/0b4516f3-1c9e-41a8-b14b-b038f07b32ee">

**Comment by chomchuen** [comment]
Primary phone option is working fine now.✅
Only Customer Primary Contact preview is pending.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/cf6f78b2-6308-4322-9c2e-f355ebb3608a)

**Comment by chomchuen** [comment]
Need solution from Umer.
So, will continue this after Muzammal and Umer don't have any urgent task left.

**Comment by chomchuen** [comment]
I tested with three cases: Phone number + Email, Email only, and Phone only. 
The issue persists only with the Phone-only case. Please check the detail below.

-> if this issue took >1.5hr, please contact me for the next step.


Phone no. + Email✅
![Image](https://github.com/zaviagodev/frappe/assets/120152434/b65409c9-0e1a-4ddc-b701-7f5dc87f15eb)

Email only✅
![Image](https://github.com/zaviagodev/frappe/assets/120152434/34f75644-fa22-4b6c-b03d-671145a55132)

Phone only❌
![Image](https://github.com/zaviagodev/frappe/assets/120152434/67531667-4d06-43bb-9cf5-3f32b22cbe88)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/3ba36c79-a535-46a4-b154-1f9b6d2559df)

**Comment by chomchuen** [comment]
Issue above is fixed.✅ @Muzmal 
But I just found issue when 'Saving' the document and 1 question.

1. In this video, first, 'Did we have any script that have added to hide _Enabled_ label??'

2. Please focus on 'Not Saved' label. After I clicked SAVE, document was saved for a sec and instantly changed to Not Save. So I need to click SAVE button again to resolve this issue.
https://www.loom.com/share/1efef102be29475cbfaa712ef6589fbd?sid=6cb28c3e-4ca4-48f9-a51c-603c94c524bb

**Comment by John-zaviago** [comment]
This is since **Jan 8,** please focus or takes contact with senior and close it within next few days @Muzmal
