### ISSUE TITLE
Notifications Menu on the side bar update & Dashboard link

### ISSUE THREAD

**Issue by MarkSuttirak** [zaviagodev/frappe#18]
We need the Notifications menu on the side bar to link to /app/notification-log 

So the user can see thier own notficiation in a full screen

![Image](https://github.com/zaviagodev/frappe/assets/62638753/e40bb8ee-eae0-4025-a9a3-e668fbe09f8c)

**Comment by John-zaviago** [comment]
Fixed - and tested. look good to me.
