### ISSUE TITLE
Select 'Preferred Billing' & 'Preferred Shipping' for 1st address /app/contact

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#182]
ERPnext have 2 methods to create customer. First is quick entry and second is full form.
In this issue, we are talking about adding new customer via 'full form'

- Quick Entry (if I added Address through this form, address I added will be automatically  selected to both Preferred Billing Address and Preferred Shipping Address by default)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/354bda9d-a95f-4d68-bf2d-9c1a6975bb6c)

- Full Form
![Image](https://github.com/zaviagodev/frappe/assets/120152434/026fc485-e86c-430a-a8ab-3866d2e7979b)

----

### Condition&Expectation:
If a customer didn't have an address information before, the first address added to the system will automatically select both Preferred Billing Address and Preferred Shipping Address.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/3a8f13b6-7cb1-4333-a94d-e4bc226f967d)

**Comment by chomchuen** [comment]
Now, the system automatically sets 'Preferred Billing Address/Shipping Address' as the default for every new address. What if we consider selecting 'Preferred Billing Address/Shipping Address' only for the customer's first address?

but if we can't do that. we can use current solution.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/4846ea33-d6d2-41a4-8bc6-175d43a20a5d)

**Comment by Muzmal** [comment]
( Pending Review )

**Comment by chomchuen** [comment]
Hello, please consider this customer.

1. This is the fresh customer. No linked contact No linked address.
https://apps.hosting.zaviago.com/app/customer/chomchom10

2. Then, I want to add a new address.
<img width="1100" alt="Screen Shot 2567-01-22 at 11 45 43" src="https://github.com/zaviagodev/frappe/assets/120152434/ec213e38-af58-4802-a713-5e5971babf68">

3. This address will be both **"Preferred Billing Address" and "Preferred Shipping Address"**
<img width="1341" alt="Screen Shot 2567-01-22 at 11 46 32" src="https://github.com/zaviagodev/frappe/assets/120152434/2986d2f7-c003-4afc-8e98-56d6769e3645">

4. Now, I have 1 address which is **"Preferred Billing Address" and "Preferred Shipping Address"**
<img width="1341" alt="Screen Shot 2567-01-22 at 11 53 12" src="https://github.com/zaviagodev/frappe/assets/120152434/d14dbf6c-41db-4af5-aa0f-d03ecef26b64">

5. but after that I want to add a new address again. which is the alternative address.
<img width="951" alt="Screen Shot 2567-01-22 at 11 56 28" src="https://github.com/zaviagodev/frappe/assets/120152434/eb454f68-b503-46f1-ae7b-4519f8521b7b">

6. But... every new address I've added is selecting **"Preferred Billing Address" and "Preferred Shipping Address"** option. 
So if I didn't unselect these option, every my new address will be **"Preferred Billing Address" and "Preferred Shipping Address"**
<img width="1319" alt="Screen Shot 2567-01-22 at 11 57 41" src="https://github.com/zaviagodev/frappe/assets/120152434/a6acc72b-0b0c-414b-bcb7-e789ed0f5f0b">

So, can you check your condition and script again? Finally If the condition doesn't work, we can simply set **"Preferred Billing Address" and "Preferred Shipping Address"=1** as a default.

**Comment by chomchuen** [comment]
It works now.🔥🔥🔥 perfectttt

<img width="958" alt="Screen Shot 2567-01-24 at 15 06 38" src="https://github.com/zaviagodev/frappe/assets/120152434/d2c9aed3-84a3-4e32-8a19-976e31b90636">
