### ISSUE TITLE
Issue in Sale Invoice when create new with image does not working

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#184]
When create a new Sale Invoice- the image does not working - we need to make sure that this is working on all predeployed site so the enduser does not have the same issue

/app/sales-invoice/new-sales-invoice

![Image](https://github.com/zaviagodev/frappe/assets/62638753/1fd4608d-22c8-40d7-b7d5-bcbf8d0c862d)

**Comment by deviljutt** [comment]
its completed

**Comment by John-zaviago** [comment]
Done - but let see when we deploy the real fixture to pre-deployment site
