### ISSUE TITLE
Removed image in Attachments on /app/item & /website-item

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#186]
How should we manage the attachments function? 

The problem is, attachments that located on the left side of the interface **display all images that were previously attached to the current item**. As a result, some users may be confused as to why images that have been removed still appear there.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/623c0ba9-5eba-4d08-bdf7-015f540b97b5)

**Comment by chomchuen** [comment]
@John-zaviago @umer2001 🙏

**Comment by chomchuen** [comment]
Noted. @umer2001 
please let me know when this's ready for review. Thank you.

**Comment by umer2001** [comment]
@chomchuen  its ready to test/review on tmp.zaviago.com

**Comment by chomchuen** [comment]
@umer2001 Thank you. I tested already. please check issue below.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/6db70b6a-8f3f-47af-a4a3-48de21814c60)

After refresh the page. Image I deleted still there but has removed from attachment.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/5960c85f-ad03-4589-b893-1a73d0feadcc)


in video.
https://www.loom.com/share/8174294ca9df49319c15aa260e9469dd?sid=6e88b9eb-9884-4ede-b471-06d173566a60

**Comment by John-zaviago** [comment]
please push it to app.hosting @umer2001

**Comment by John-zaviago** [comment]
This seem to be fix
