### ISSUE TITLE
Customize dashboard registration step

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#188]
Registration flow was changed.  Can you check and customize the registration flow according to this design?

https://www.figma.com/file/bUToY0sNiFGik4KbOBOTP2/New-Andromeda-(Test-Prototype)?type=design&node-id=3299%3A14785&mode=design&t=gdrWaT5y2LDpZFN1-1

Please check from this page.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/2c1423d3-fe64-415e-b42c-0e5ae0976c84)

**Comment by deviljutt** [comment]
its also complete there is issue on OTP i am debugging that

**Comment by John-zaviago** [comment]
@chomchuen please review and comment your finding here thank

**Comment by chomchuen** [comment]
loading forever. Hard refresh can't resolve this. @deviljutt 

![Screen Shot 2567-01-29 at 11 15 54](https://github.com/zaviagodev/frappe/assets/120152434/e36f5910-63a6-4dd1-8ce9-297d11cd1751)

**Comment by chomchuen** [comment]
I tried to login again. Sign up step was skipped. I can access main dashboard without the completion of sign up step. @deviljutt 

![Screen Shot 2567-01-29 at 11 25 30](https://github.com/zaviagodev/frappe/assets/120152434/645f7669-f0bd-40e7-b82f-7ac54522dab7)

**Comment by John-zaviago** [comment]
@deviljutt this seem to be big issue, that it skiped steps / please check

**Comment by chomchuen** [comment]
**Step 1 : Phone No. Verification.**
- [x] Received an OTP.
- [ ] Resend an OTP.

**Step 2 : Register / Site Setup**
- [ ] No 'Name' field
- [ ] No consent checkbox
- [ ] Design part is need to edit.
- [ ] Stuck on register page wasn't redirected to dashboard main page. (can check from the end of video)

![Image](https://github.com/zaviagodev/frappe/assets/120152434/1a077b06-e26b-40ec-abc3-26aba6d08f60)

Expectation:
![Image](https://github.com/zaviagodev/frappe/assets/120152434/77969c5b-2ee7-4c24-9bff-c104863fb87b)

video--> https://youtu.be/U91T4liClh4

**Comment by John-zaviago** [comment]
Unable to duplicate the  issue from @deviljutt side. -

**Comment by John-zaviago** [comment]
For resend otp is not working. and the time count is not working-.

**Comment by John-zaviago** [comment]
Need me to review -

**Comment by chomchuen** [comment]
Site wasn't created. Resend OTP isn't working. @deviljutt @John-zaviago 

https://www.loom.com/share/6cddbae2bf06458a94236fd4230880b4?sid=413fdf4a-f054-4d18-9c34-dedd7be51c82

**Comment by John-zaviago** [comment]
@deviljutt did you check this?

**Comment by John-zaviago** [comment]
fixed from last night
