### ISSUE TITLE
Merge Branch in Frappe Repo to Main and Update App.hosting.zaviago.com

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#194]
**Task: Merge Branch in Frappe Repo to Main and Update App.hosting.zaviago.com**

**Task List:**
1. Merge the Mark CSS branch in the Frappe repository to the main branch.
2. Update the master version of the Frappe app on Apps.hosting.zaviago.com to reflect the changes.

**Implementation Steps:**
1. Access the Frappe repository and navigate to the specified branch.
2. Perform a merge of the specified branch into the main branch.
3. Resolve any merge conflicts if they arise during the merging process.
4. Push the changes to the main branch in the Frappe repository.
5. Update the master version of the Frappe app on App.hosting.zaviago.com to synchronize with the latest changes.

**Expected Outcome:**
The specified branch changes should be successfully merged into the main branch in the Frappe repository. Additionally, the master version of the Frappe app on App.hosting.zaviago.com should be updated to reflect the merged changes.

**Additional Information:**
Ensure that any potential conflicts during the merge process are addressed appropriately to maintain code integrity.

**Comment by deviljutt** [comment]
This is done


![Image](https://github.com/zaviagodev/frappe/assets/29252752/61bf3af8-8499-4a1f-9796-fdad3032a838)

**Comment by John-zaviago** [comment]
Seem to be done and fixed the css issues.
