### ISSUE TITLE
Issue in Customer Doctype script

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#198]
https://www.loom.com/share/0e24cc89bf3a46c893b56d9173689734

Issue as seen in video, it seem that everytime it load in the data it takes very long time, but also sometime dont work at all

**Comment by Muzmal** [comment]
@John-zaviago   You can check

**Comment by chomchuen** [comment]
Need to optimize loading speed.

**Comment by Muzmal** [comment]
Speed is good now

**Comment by chomchuen** [comment]
@John-zaviago The speed depends on the transaction the customer has.

**Comment by John-zaviago** [comment]
Muzzalmal need your input @umer2001

**Comment by chomchuen** [comment]
Now, uses only 3sec to load customer data that have 75 Sales invoices.
