### ISSUE TITLE
Activity comment is aligned in middle issue

### ISSUE THREAD

**Issue by MarkSuttirak** [zaviagodev/frappe#20]
the comment, should align left. not in the middle

![Image](https://github.com/zaviagodev/frappe/assets/62638753/e75e1e55-6908-4abe-93f2-d01b46c9866b)

**Comment by John-zaviago** [comment]
![Image](https://github.com/zaviagodev/frappe/assets/62638753/f83ffe69-8705-4df8-a225-e320aae7d9d0)

Fixed.
