### ISSUE TITLE
Css issue with input field

### ISSUE THREAD

**Issue by MarkSuttirak** [zaviagodev/frappe#21]
there is an css issue with the select input field, as show in image below.

![Image](https://github.com/zaviagodev/frappe/assets/62638753/a8319c40-3770-4e82-89e3-4fec27408e89)

**Comment by John-zaviago** [comment]
![Image](https://github.com/zaviagodev/frappe/assets/62638753/5cc08176-deba-4f28-9b12-85002624c2b8)

fixed thank
