### ISSUE TITLE
Elementor widget panel not loading

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#219]
On intergoods.net website is facing Elementor widget panel not loading. Please investigate and solve this issue.
If this issue took >1.5hr to figure out, please contact me to find another solution.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/05b878cd-3995-4238-b1a6-b97810f68005)

**Comment by Muzmal** [comment]
![image](https://github.com/zaviagodev/frappe/assets/18447840/7aa2ca79-59cb-4446-8505-183428d221c8)
Fixed

**Comment by chomchuen** [comment]
Issue is fixed on .net as well
