### ISSUE TITLE
Get data to POS print format

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#232]
Site: Clinton06

Get data to this print format -> https://clintoncopysite06.frappe.cloud/app/print-format/Print%20POS%20Invoice

Detail: https://www.figma.com/file/Tu5e6wo6MWSOpD87kElnJj/Clinton-Print-Format?type=design&node-id=0%3A1&mode=design&t=1VJVs6UhobY3d1wf-1

**Comment by chomchuen** [comment]
Approved, but need Mark for fixing the margin a little.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/86e88e7c-6b0a-433a-b7c2-348b172b3743)

**Comment by chomchuen** [comment]
Got new feedback from Clinton team.
Please check from the same Figma. Thanks🙏 @Muzmal 

![Image](https://github.com/zaviagodev/frappe/assets/120152434/b2518c99-7420-4c54-8c67-03cfa36ff559)

**Comment by chomchuen** [comment]
Above approved✅

--- 
* new *
please set new condition to POS print format.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/dd18e129-6631-4983-aea7-4b992abcb111)

**Comment by chomchuen** [comment]
last feedback!

![Image](https://github.com/zaviagodev/frappe/assets/120152434/7c97cade-3f10-4784-b848-94bcd861ec15)

**Comment by Muzmal** [comment]
Fixed

**Comment by chomchuen** [comment]
Fixed✅

![Image](https://github.com/zaviagodev/frappe/assets/120152434/7286323b-6cee-4a42-85a0-2b7e6eef4382)

**Comment by chomchuen** [comment]
hope this is the last condition that need to be set in this print format...

![Image](https://github.com/zaviagodev/frappe/assets/120152434/115c27b4-db3f-4a52-827a-099c12c2d08d)

**Comment by Muzmal** [comment]
Fixed

**Comment by chomchuen** [comment]
New feedback from Clinton team.

Please check detail from these frame on Figma.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/f639b3ff-4419-4398-99ed-aa6090470728)

https://www.figma.com/file/Tu5e6wo6MWSOpD87kElnJj/Clinton-Print-Format?type=design&node-id=0%3A1&mode=design&t=Oedp8EIJo7hyozRh-1
