### ISSUE TITLE
Update Clinton Sales invoice print format

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#233]
### **Please test on this site -> Clinton06 (Staging site)**

Clinton want to reduce spacing on customer address. 
So I decided to get some data into the same line.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/03abdba8-8117-4c15-9708-5698c88b914b)

please check the detail from section: **Sales invoice - new getting data method for an address**
https://www.figma.com/file/Tu5e6wo6MWSOpD87kElnJj/Clinton-Print-Format?type=design&node-id=0%3A1&mode=design&t=1VJVs6UhobY3d1wf-1

![Image](https://github.com/zaviagodev/frappe/assets/120152434/c240e428-e054-4eef-85ce-1c9b478d0465)

**Comment by chomchuen** [comment]
👀 Checked and Email and Tax Id not found.
Please add email and tax id to customer address. Thank you.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/7c513837-bc70-434a-9d52-0485a5ac2838)

**Comment by chomchuen** [comment]
Fixed✅

**Comment by chomchuen** [comment]
Have an issue with blank data.
Like the img below, customer doesnt have Fax and Email data but _Fax:_ and _Email:_ text still there. So I curious if you can create the condition to hide its text? if current customer doesnt have these data.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/0f5dee6c-f575-4463-b208-27d7b6b515f1)

**Comment by Muzmal** [comment]
![image](https://github.com/zaviagodev/frappe/assets/18447840/510f59ed-25d5-44f9-83af-19f3afadc8a5)
fixed

**Comment by chomchuen** [comment]
Fixed✅

![Image](https://github.com/zaviagodev/frappe/assets/120152434/15fb0d3a-142c-4ef7-b5ed-a70cb730bd74)

**Comment by chomchuen** [comment]
"New issue found"🚨

If customers **used to** have Phone/Fax/Email and Tax ID and was removed later, Phone/Fax/Email and Tax ID will stick to the print format.

It possible to fix this case?

![Image](https://github.com/zaviagodev/frappe/assets/120152434/20b5c03b-46d1-4c3e-af13-c7cc89de00e0)

**Comment by Muzmal** [comment]
Done
