### ISSUE TITLE
Managing VAT : Sales Taxes & Charges Template/SINV doctype

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#238]
**How we manage VAT on WorkSpace??🤔**

If we allow users to add VAT and charges flexibly, we'll have to consider too many cases!. So, I think we should **restrict users from adding a new row on Tax&Charge table** and **adding a new tax template on Sales taxes & Charges template.** 🤯💥

-----
**"Related doctype"**
1. Sales Invoice Doctype
2. Sales VAT & Charges Template Doctype

----
### Expectation:

1) Restrict users from "adding a new row" & "change any things" on Sales taxes and Charges table through SINV doctype.

REF: https://discuss.frappe.io/t/hide-add-row-from-child-table/36694

![Image](https://github.com/zaviagodev/frappe/assets/120152434/c40b6a2d-871a-44d8-a656-e4cc8c03a7c7)

2) Restrict users from "adding a new row" from Sales taxes & Charges template doctype.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/d4bf0cd2-a426-4ae4-b65c-c169acc2bdf1)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/75cca70d-561c-4ccc-bdf4-528c9cb0163e)

**Comment by chomchuen** [comment]
Sales invoice seem nice. but please check detail above and check Sales VAT & Charges Template Doctype again.👍

![Image](https://github.com/zaviagodev/frappe/assets/120152434/525b26f6-1bf3-4b69-818d-4f3fbb0a025e)

**Comment by Muzmal** [comment]
Done

**Comment by chomchuen** [comment]
Please do not forget to set 'read only' to these. 👀 @Muzmal 
![Image](https://github.com/zaviagodev/frappe/assets/120152434/7f0d1636-4a3f-431d-a96d-d7cddf83f118)

**Comment by Muzmal** [comment]
Done.
Complete
