### ISSUE TITLE
Can't submit old SINV! (due date issue)

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#239]
**Expectation**
- Clear data in the Payment Schedule Table for users to prevent the warning message below.

----
This warning is ok.
![Image](https://github.com/zaviagodev/frappe/assets/120152434/17c69d03-4b2b-4a00-bd57-2124937c7641)

but I don't want users see this warning🥲.

Concern: If site is working heavy & slowly, between 'this warning' message or 'clearing data in the table', which one would happen first?? 🤔

![Image](https://github.com/zaviagodev/frappe/assets/120152434/77d48d01-1427-41c6-b3fc-141f470a8ee6)

**Comment by Muzmal** [comment]
Fixed!
Regarding your concern the answer is that, script will clear the table before saving. that means even if site is slow, user will not get this message

**Comment by chomchuen** [comment]
@Muzmal 
Can you check the script?  Why I'm able to submit a Sales Invoice even if it has a past due date🤔?

![Image](https://github.com/zaviagodev/frappe/assets/120152434/d8a275aa-5b18-401a-bc2f-3fe69b75e64e)

**Comment by Muzmal** [comment]
![image](https://github.com/zaviagodev/frappe/assets/18447840/e38c249e-d1e5-4863-9dab-d96c89ae1735)

i got this message

**Comment by Muzmal** [comment]
![image](https://github.com/zaviagodev/frappe/assets/18447840/334645f6-4799-49d2-aebc-b5eb8fecc4c0)
this is working fine now. you can check and close the issue

**Comment by chomchuen** [comment]
I'm still able to submit past payment due date invoice. without any warning message. because of permission?🤔 you can try from my account.

username: chomchuen@zaviago.com
password: zaviago.com

https://www.loom.com/share/1be0f1b79e504e9fb52b4572fe8f167d?sid=477ea79b-3d0a-45f4-b693-def0a2ace2dd

**Comment by chomchuen** [comment]
I'm still able to submit past payment due date invoice. without any warning message. because of permission?🤔 you can try from my account.

https://www.loom.com/share/1be0f1b79e504e9fb52b4572fe8f167d?sid=477ea79b-3d0a-45f4-b693-def0a2ace2dd

**Comment by chomchuen** [comment]
Changed requirement!

- Users must be able to submit 'PAST' sales invoice.
- Users must be able to create 'PAST' sales invoice.

status will change from draft to overdue directly.

**Comment by Muzmal** [comment]
Done

**Comment by chomchuen** [comment]
Not sure🤔 but you can try to disable due date function for checking Issue no.4 (insufficient stock) https://github.com/zaviagodev/frappe/issues/244.

because I found insufficient stock warning in the morning and I added the stock to this item and then I can submit the sales invoice.
