### ISSUE TITLE
Sales Invoice Activity

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#243]
Please check if it possible to track 'Payment' & 'Shipping' activity?

Detail: https://apps.hosting.zaviago.com/app/sales-invoice/ACC-SINV-2024-00213
Display "Who" added "Payment" and "Who" added "Tracking number"

Example: **chomchuen@zaviago.com** created/added Payment.
**chomchuen@zaviago.com** created/added Tracking number: **1100291212434**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/307b8814-487b-4bbc-8e39-15789fae3a39)

**Comment by Muzmal** [comment]
Done
![image](https://github.com/zaviagodev/frappe/assets/18447840/d9c5c21c-23bb-4a79-83aa-85d51135da2d)

**Comment by chomchuen** [comment]
Adding Payment

- added rows for **???**

Can you add the table name (or maybe another thing else) to not let the activity message be blank?

![Image](https://github.com/zaviagodev/frappe/assets/120152434/954b130c-44e4-4ec2-8146-6508fbf9bf47)

**Comment by chomchuen** [comment]
Fixed

![Image](https://github.com/zaviagodev/frappe/assets/120152434/3b24a9ce-162f-4bb8-8cf0-2825d07ec947)
