### ISSUE TITLE
Issue with Pricing rules features at pricing tab in /item/

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#25]
![Image](https://github.com/zaviagodev/frappe/assets/62638753/e613be80-c1bc-40ca-b3e7-1b8f02075d01)

### 1. Issue Description
There is an issue where adjustments to sale prices in the Item's pricing tab are not being correctly reflected in the Super Admin's Pricing Rules. New pricing rules created are not linked to the items they are supposed to be connected to.

### 2. Steps to Reproduce
1. Log in to Frappe ERPNext beta instance at `beta.zaviago.com` with the following credentials: `user@zaviago.com` / `zaviago.com`.
2. Navigate to `../app/item/` and access the pricing tab.
3. Click on the "On Sale" checkbox to adjust or create a new sale price for an item.
4. As a Super Admin, navigate to Connection -> Pricing Rules.
5. Observe the lack of connection between the adjusted prices and the specific items.

### 3. Current Behavior
- Adjusting item prices via the "On Sale" box leads to the creation of new pricing rules.
- These new rules are not linked to the intended items.

### 4. Expected Behavior
- Pricing rules adjusted or created through the Item's "On Sale" feature should be directly connected to the items.
- Any adjustments to pricing should update the existing pricing rules, not create new ones.

### 5. Goal
To correct the pricing rule adjustment flow so that any changes made through the Item's "On Sale" feature are accurately reflected in the Pricing Rules section, thereby preventing the creation of unlinked rules.

### 6. Action Items
- [ ] Investigate the linkage mechanism between Item pricing adjustments and the Pricing Rules module.
- [ ] Diagnose why new pricing rules are not associating with their items.
- [ ] Develop and implement a solution to ensure that item pricing adjustments update existing rules.
- [ ] Conduct thorough testing to confirm that the issue is resolved.
- [ ] Update any relevant documentation with the new procedure for adjusting pricing rules.

**Comment by John-zaviago** [comment]
Related to nabeel issue with permission when create new product and the item price have some issue.

**Comment by chomchuen** [comment]
**Step 2 - Sale Price** show the wrong value (still shows previous value and didn't change to new value)
but sale price in Pricing Summary section & pricing rule & transaction is show correct value.

https://www.loom.com/share/f6fd9970907c4ffdb2eeee8e4d95a06b?sid=bf7ae996-30f5-45a7-8cc2-2e4a7192974b

**Comment by chomchuen** [comment]
Can't set discount value to be decimal number.

-> discount value should support 2 decimal places value.
ex. _Full price_ 350 - _discount value_ 150.25 = _sale price_ 199.75

<img width="1320" alt="Screen Shot 2567-01-18 at 10 52 58" src="https://github.com/zaviagodev/frappe/assets/120152434/dadee93e-3642-49ca-977b-7cda4c412a4b">

**Comment by Muzmal** [comment]
( Pending Review )

**Comment by chomchuen** [comment]
Fixed both percentage and amount discount type.✅

<img width="886" alt="Screen Shot 2567-01-22 at 13 32 36" src="https://github.com/zaviagodev/frappe/assets/120152434/f113066f-0487-446c-be3b-b21eee8e508d">

![Screen Shot 2567-01-22 at 13 32 30](https://github.com/zaviagodev/frappe/assets/120152434/a05723c6-ad33-4ed5-886f-b822993b4baf)
