### ISSUE TITLE
/app/website-item/ Unable to read file format warning when save.

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#28]
## Issue: Warning Message on Image Upload in Website Item

There is a user experience issue within the Website Item DocType. After uploading an image to a website item and saving, a warning message is displayed stating: "Unable to read file format for https://media-cdn.bnn.in.th/332577/iPhone_15_Plus_Pink_2-square_medium.jpg". This warning can lead to confusion and a negative user experience as it suggests that the image upload was unsuccessful or incorrect, even if the image format is supported.

## Steps to Reproduce
1. Go to the Item section.
2. Click on 'Website Item'.
3. Select any existing website item.
4. Upload an image to the Website Item DocType.
5. Save the entry.
6. Observe the warning message about the file format.

## Expected Behavior
- The system should properly read and process the image file without displaying an error or warning, assuming the file format is supported.
- If the image format is indeed unsupported, the system should provide a clear and actionable error message before the save attempt.

## Goals
- Ensure that the image upload feature works without displaying incorrect warnings.
- Provide clear feedback to users if there is an actual issue with the image format.

## Action Items
- Investigate the cause of the warning message and determine whether it is a file format issue or a bug in the image processing logic.
- Review the supported image formats and ensure the system's image processing is compatible with common image file types.
- If necessary, update the image processing function to handle the supported formats correctly.
- Implement a more descriptive error handling process to guide users in the case of genuine format issues.
- Test the image upload functionality to ensure the warning message does not appear when correctly formatted images are uploaded.

## Importance
Resolving this issue is crucial for maintaining a seamless and professional user experience. The current warning message could lead to unnecessary concerns or attempts to re-upload images, wasting users' time and potentially causing frustration.

## Request for Immediate Attention
Please address this with urgency to prevent any impact on our users' confidence in using the platform for website item management.

Thank you for your prompt action to resolve this matter and enhance the usability of our system.

![Image](https://github.com/zaviagodev/frappe/assets/62638753/7e91428e-f66a-47e4-8183-99170e968cd8)

**Comment by chomchuen** [comment]
seem this issue was solved.
maybe we just need to change UX writing of warning modal.
