### ISSUE TITLE
CI CD issue -  CSS Changes Not Reflecting in Production on Frappe v15

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#31]
### 1. Issue Description
CSS changes pushed to the repository are not being updated in the production environment. This issue is currently observed in the Frappe framework version 15, affecting the beta.zaviago.com site.

### 2. Steps to Reproduce
1. Push CSS changes to the repository.
2. Observe the CI/CD pipeline executing the deployment process.
3. After deployment, check the production site at beta.zaviago.com for the reflected changes.

### 3. Current Behavior
- The CSS changes made in the repository are not visible on the production site after the deployment process.

### 4. Expected Behavior
- All changes made to CSS files and pushed to the repository should be reflected in the production environment upon successful deployment.

### 5. Action Items
- [ ] Review the commits related to CSS changes to confirm they are correctly pushed to the repository.
- [ ] Examine the CI/CD pipeline configuration, specifically the steps handling CSS files.
- [ ] Inspect the build and deployment logs for any errors or warnings that could indicate why CSS changes are not being applied.
- [ ] Confirm that the latest code version is being deployed to the beta environment.
- [ ] Check server-side caching mechanisms that might prevent updated CSS from being served.
- [ ] If necessary, manually trigger the build and deployment to ensure the changes are picked up.
- [ ] Communicate with the development team to gather more insights into the issue.
- [ ] Apply a fix to the CI/CD pipeline and document the resolution process for future reference.

**Comment by deviljutt** [comment]
@MarkSuttirak can you confirm if this version have your changins?  idk about the changings so i can't confirm but from now it will fetch the version-15 changings

**Comment by John-zaviago** [comment]
Need to contact umer on this one

**Comment by John-zaviago** [comment]
- some of the command was not running in CI CD pipeline- 

1h
