### ISSUE TITLE
Upgrade to Pro button in frappe top bar - redirect to an upgrade page in react

### ISSUE THREAD

**Issue by MarkSuttirak** [zaviagodev/frappe#39]
## Feature Request: Redirect Functionality for 'Upgrade to Pro'
As part of enhancing the user journey within our platform, we need to establish a redirect for the 'Upgrade to Pro' button located in the Frappe top bar. The button should lead users directly to a dedicated upgrade page within our React-based dashboard.

## Current Behavior
Currently, the 'Upgrade to Pro' button does not redirect users to the intended upgrade page, which is likely affecting our conversion rates for upgrades.

## Expected Behavior
Upon clicking the 'Upgrade to Pro' button, users should be taken to an upgrade page on our React dashboard where they can view the benefits of upgrading and complete the process.

## Goals
- To streamline the upgrade process for users.
- To improve the visibility and accessibility of the upgrade options.
- To increase the conversion rate for users upgrading to the Pro version.

## Action Items
- Implement the redirect functionality for the 'Upgrade to Pro' button.
- Ensure the destination page clearly communicates the benefits and process of upgrading.
- Test the redirect to ensure it works seamlessly across various browsers and devices.

## Importance
This update is critical for providing a clear path for users considering an upgrade, which is an essential step in our funnel for revenue growth.

## Request for Action
Please prioritize this task as it directly impacts our business model and user satisfaction.

Thank you for your prompt attention to this request.

**Comment by MarkSuttirak** [comment]
I have changed the link when clicking the 'Upgrade to Pro' button on the top bar to https://zaviago-dashboard.vercel.app/dashboard/compare-plan, please check whether I set the correct link or not. Thank you.

**Comment by John-zaviago** [comment]
Review close
