### ISSUE TITLE
Remove Item Overview Page

### ISSUE THREAD

**Issue by Fyn5** [zaviagodev/frappe#43]
## Situation
User have a permission to entry Item Overview from Awesome bar 

## Action need:
Remove Item Overview Permission from User

![Image](https://github.com/zaviagodev/frappe/assets/120152401/e5fde372-37a1-4a18-9344-e9eba93c4b15)

## Following Issue
When User search module from Awesome bar, it appear the sidebar menu from frappe that we have config to hidden this sidebar.

**Comment by John-zaviago** [comment]
I can confirm that the sidebar is removed from Super Admin but not for other normal admin user @deviljutt need to fix this

**Comment by John-zaviago** [comment]
Fixed. but john need to create dashboard
