### ISSUE TITLE
Implement Image Preview on Hover in Payment Details Table

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#49]
![Image](https://github.com/zaviagodev/frappe/assets/62638753/baa16df2-dce1-4195-af54-6409151f5100)

## Feature Request: Hover Image Preview in Sales Invoice Payment Details

We have identified a missing functionality within the Sales Invoice module, specifically in the Payments tab. The 'Payment File' column within the payment details table is intended to have an image preview on hover, a feature that is currently not operational.

## Current Behavior
When users hover over an image file within the 'Payment File' column, there is no preview displayed, which hinders their ability to quickly verify or view the image without clicking to open it.

## Desired Functionality
- Implement a hover functionality that triggers an image preview popup when users hover over image files in the 'Payment File' column.
- The preview should be a lightweight overlay that doesn't obstruct other interface elements and closes when the mouse moves away.

## Goals
- To enhance user experience by allowing quick and convenient previews of images.
- To improve workflow efficiency by reducing the need to fully open image files for verification.

## Action Items
- Review the existing function for image preview on hover within the Frappe framework.
- Implement the hover preview feature for the 'Payment File' column in the payment details table.
- Ensure that the implementation is cross-browser compatible and responsive to different screen sizes.
- Conduct thorough testing to confirm the functionality works as intended across various scenarios.

## Importance
This functionality is an important aspect of the user interface that contributes to an efficient and streamlined workflow, particularly for users who handle numerous transactions.

## Request for Implementation
Please prioritize the restoration of this image preview feature, ensuring it aligns with our standards for a functional and user-friendly interface.

Thank you for your prompt attention to this request and your commitment to continuous improvement of our system.

**Comment by chomchuen** [comment]
-need Umer suggestion-

**Comment by umer2001** [comment]
fixed by commit: https://github.com/zaviagodev/frappe/commit/d23ad58d187dd04223916abc0f734dad138d4d58
