### ISSUE TITLE
Additional functionality of "Payment Entry"

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#70]
Please change default setting of ERPnext according to this.

1. Set **Party Type** = Customer as a default

![Image](https://github.com/zaviagodev/frappe/assets/120152434/00faae0b-2c9a-4764-b307-a0267d3e6339)

2. Add **Bank** from Bank doctype to Payment Entry

![Image](https://github.com/zaviagodev/frappe/assets/120152434/01770323-b38c-4e54-8893-067cf63d282b)

3. Set **Account paid to** =  default (because we will hide this field and do not let users select this.)

![Image](https://github.com/zaviagodev/frappe/assets/120152434/9691d66e-9ab3-49d5-a7f5-f1aef6d42ad5)

**Comment by Fyn5** [comment]
the default account paid to is Accounts Receivable - WS

**Comment by chomchuen** [comment]
only no.2 is pending.

**Comment by Muzmal** [comment]
Done. You can check

**Comment by chomchuen** [comment]
-Approved-
