### ISSUE TITLE
"Sales Invoice" doctype customization

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#75]
### Priority

🥇 Design : move field, add field, create new section etc.

🥈 Client Script, Server Script.

🥉 Sync Sales Channel/Bank with logo. 

Do this for the last = status label.

----

### Goal🎯

- Hide and add fields to make item doctype exactly same as design in Figma.
- Check and change typo and field name to be same as design.
- Create functionally that not take a lot effort to complete.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/d8d54f08-ff76-4f2c-9929-ad8a64960a24)

-----
Please check the detail in Figma link via.
https://www.figma.com/file/juJvQnFZDW11ld2lxQsIZ0/Doctype-Cuztomization?type=design&node-id=0%3A1&mode=design&t=jRJhZEV2lQatdNoZ-1

**Comment by chomchuen** [comment]
updated new feedback on Figma.🔥


![Image](https://github.com/zaviagodev/frappe/assets/120152434/e60b376e-b5f6-4a26-9af8-88cbd03bdaf2)

**Comment by chomchuen** [comment]
- **Order amount doesn't work both on create and saved.**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/faf7cb7d-a1a3-426d-87d7-6c4449323dd9)



![Image](https://github.com/zaviagodev/frappe/assets/120152434/eea89f0a-d476-44f2-b72c-94f6990e421f)

**Comment by chomchuen** [comment]
**on create**
- pending..

**on saved**
- done✅

<img width="1172" alt="Screen Shot 2566-12-28 at 14 09 10" src="https://github.com/zaviagodev/frappe/assets/120152434/89960a6e-eaeb-4e68-a621-b633ea45d43b">

**Comment by chomchuen** [comment]
**on create**

- done✅

<img width="1126" alt="Screen Shot 2566-12-29 at 10 59 19" src="https://github.com/zaviagodev/frappe/assets/120152434/bbe3ac7b-3ce5-4deb-8836-f87baf517ba0">

**Comment by chomchuen** [comment]
- [x] 1
-> **Please add 'Awaits Shipping' label (same like details tab) if no shipping no. added yet.**
- [ ] 2
- [ ] 3
-> **2&3 happened if order came from Storefront. Do you have any solution for this? (https://apps.hosting.zaviago.com/store)**
- [x] 4
-> **Please check detail from latest comment.**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/36b1e06d-268c-4701-aee4-7587485df7c9)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/8e67d899-d729-419f-a3ca-4077611141bc)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/1d253dda-74d0-4eb9-b6df-248722aff5cd)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/a80a8013-9d67-49c8-b07d-ab287bcfc007)

**Comment by chomchuen** [comment]
**✅ Fixed.**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/829214d5-de25-4bf5-a24f-ea35e8fc8e84)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/d5c96d7f-9309-4d45-87a5-14a9aaf6089d)

**Comment by chomchuen** [comment]
Fixed✅

![Image](https://github.com/zaviagodev/frappe/assets/120152434/69d8a400-39e0-4f21-93eb-60e093aafb32)

---

This is the 1st order for the customer 'Chomchom15'. However, the Total Order and Total Items Bought fields do not appear on this page.
(Total Order and Total item brought will be "0" for this order)

---

In the current scenario, these fields will only appear if they have a value >1.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/37567a59-e4c6-4224-8880-de8fb78ac943)

**Comment by chomchuen** [comment]
Only point 2&3 that related with Storefront are pending.

**Comment by Muzmal** [comment]
points 2 and 3 are also fixed

**Comment by chomchuen** [comment]
**Storefront SINV fixed✅**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/9cd99b58-c3d2-4f6f-8833-94d68fc60262)
![Image](https://github.com/zaviagodev/frappe/assets/120152434/7033eb39-8ec3-4f2b-bad9-7417cf713244)
