### ISSUE TITLE
Issue with Product Creation and Pricing Permissions for Store Admin Users

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#8]
## Issue Description
We have encountered a permission issue during the product creation process, particularly with the pricing aspect as it relates to the function managed by Nabeel.

## Problem Statement
When a Store Admin user attempts to add a new product and enters a price into the "Item Price" field on the Details tab, an error occurs upon saving. Despite the error message, the product is still created in the system, which is misleading because the interface suggests that the product has not been added. This has led to confusion among the users. - 

**However, yes it is correct that user should not be able to create a new item price list as they should only use current function we proivde with Server script and Client script to edit the price** 

## Steps to Reproduce
1. Log in as a Store Admin. user@zaviago.com passwork: zaviago.com
2. Navigate to the product creation section under Items.
3. Enter the necessary details along with the price in the "Item Price" field.
4. Click on 'Save' to create the product.
5. Observe the error message and the page's failure to redirect.
6. Return to the item table to see that the product has been created regardless of the error.

## Expected Behaviour
When the Store Admin adds a product and price details and clicks 'Save', the product should be created without any errors, and the user should be redirected appropriately, confirming the creation of the item.

## Impact
This permission issue is causing significant confusion and may lead to duplicated efforts or overlooked products due to the misleading error message.

## Required Action
Investigate the permission settings related to the "Item Price" field and the product creation process for the Store Admin role. Determine whether the error is a result of incorrect permissions or a bug in the function managed by Nabeel.

Make sure you fix it with Server Script, or Clients Script or otherway that we can export this features to other frappe deployment

## Deadline
Please prioritize this issue and provide an update on the progress as soon as possible.

Thank you for your immediate attention to this matter.

__

**Comment by John-zaviago** [comment]
![Image](https://github.com/zaviagodev/frappe/assets/62638753/15cc7689-65fe-47fe-83b1-8ac6f1b39601)

**Comment by Fyn5** [comment]
**### Checking on the permission:**


![Image](https://github.com/zaviagodev/frappe/assets/120152401/95a898e4-1b47-468d-b7c2-de41745ccac6)

As alert message, the permission need to set CREATE and READ therefore user can WRITE the Item Price

as well as Price List doctype, if need.


![Image](https://github.com/zaviagodev/frappe/assets/120152401/a9b07c47-538c-424c-b4e6-156551371e67)

**Comment by Fyn5** [comment]
@John-zaviago do you want me to set the permission CREATE/READ for Store Admin role?

**Comment by John-zaviago** [comment]
it appears that the initial issue with the 'Item Price' field has been resolved. Store Admin users are now able to use the predefined functions, as intended, without encountering the error message. This ensures that product creation and pricing updates are conducted smoothly and align with our server script and client script configurations for pricing management.

https://www.awesomescreenshot.com/video/22470868?key=50e365841c1da6a8a7c9924909092ed1

**Comment by Fyn5** [comment]
As discussed, I still think that to add role permission (CREATE/READ of item price) at its core is still need to allow user to CREATE/READ new item but we need to think on hidden the connection at View level instead.

@John-zaviago what do you think?


However I have removed the role permission CREATE/READ for Store Admin role as our conversation this morning.
http://beta.zaviago.com/app/permission-manager/Item%20Price
http://beta.zaviago.com/app/permission-manager/Price%20List

**Comment by John-zaviago** [comment]
Reopen issue for Nabeel to take a look

**Comment by John-zaviago** [comment]
Reconnected field - and then retest again
