### ISSUE TITLE
Auto-Fetching Preferred Shipping Address in Sales Invoice Customer Creation

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/frappe#9]
## Issue Description
During the process of creating a new sales invoice, when a user adds a new customer through the 'New Customer' popup modal, the information is saved to the database. However, after saving, when the modal closes, the user remains on the 'Create New Sale Invoice' page with the new customer data pre-filled. The issue arises with the shipping address not being auto-filled, requiring the user to manually click the Shipping Address field to fetch the address again, which increases the number of clicks and reduces efficiency.

## Steps to Reproduce
1. Go to 'Create New Sale Invoice' page.
2. Click to add a new customer, which opens the 'New Customer' popup modal.
3. Fill in the customer information, including the primary address details.
4. Save the new customer, which closes the modal and returns to the invoice page.
5. Notice the customer field is pre-filled, but the shipping address field is not.

## Expected Behavior
The primary address details entered in the 'New Customer' modal should be automatically set as the 'Preferred Shipping Address'. This would allow ERPNext to auto-fetch the preferred address, minimizing user actions and streamlining the invoice creation process.

## Goal
To enhance user experience by reducing the number of clicks and manual data entry required when creating a new sales invoice after adding a new customer.

## Action Items
- Modify the quick entry feature for the 'New Customer' modal to set the primary address as the 'Preferred Shipping Address'.
- Ensure the system auto-fetches this address into the Shipping Address field on the sales invoice page.
- Conduct thorough testing to confirm that the address is auto-fetched correctly.

## Importance
This enhancement is critical for improving the user experience and operational efficiency for our sales team.

## Request for Implementation
Please prioritize this issue to simplify the sales invoice creation workflow. Adjustments to the quick entry modal logic are required to ensure the 'Preferred Shipping Address' is automatically populated.

Thank you for your attention to this necessary improvement.

**Comment by chomchuen** [comment]
![Image](https://github.com/zaviagodev/frappe/assets/120152434/e9c3298e-05b0-44e8-af8a-a83e440e9dab)

estimated time: 1-2 hr. on 16 Nov Morning

**Comment by Muzmal** [comment]
Server script is used to fix issue
